spring.application.name=notification-service

server.port=8086

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ticket123}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#kafka consumer
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:notification-service-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
notification.topic.order-confirmed=${ORDER_CONFIRMED_TOPIC:order-confirmed-topic}


