spring.application.name=payment-service
server.port=8085
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_payment_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ticket123}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Redis (ticket locking)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# service
user.serivce.url=${USER_SERVICE_URL:http://localhost:8081/api/v1/users}
