spring.application.name=user-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_user_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ticket123}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# JWT CONFIG
# Key secret generate JwtSecret.generateNewSecret()
# expiration 3600 seconds equal 1 hour
jwt.url=/api/public/users/login
jwt.header=Authorization
jwt.prefix=Bearer 
jwt.expiration=3600
jwt.secret: ${JWT_SECRET:wM0mBxIDFKh1FOCWfA++ZCSk8d1I8ztVZAOxdqxtiXxOmb8yF9UCwIZ8MMCGHptU}
default-password: ${DEFAULT_PASSWORD:}
