spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_user_db
spring.datasource.username=ticket
spring.datasource.password=ticket123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
