spring.application.name=order-service
server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ticket123}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#service
event.service.url=${EVENT_SERVICE_URL:http://localhost:8082/api/v1/events}
user.service.url=${USER_SERVICE_URL:http://localhost:8081}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8085/api/v1/payments}

#kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
notification.topic.order-confirmed=order-confirmed-topic