spring.application.name=event-service

server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_event_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ticket123}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


